# Generated by Django 5.1 on 2024-08-26 00:46

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Male'), ('Femenino', 'Female'), ('Otro', 'Other'), ('Desconocido', 'Unknown')], default='Masculino', max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=64)),
                ('message', models.CharField(blank=True, max_length=128, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('priority', models.CharField(choices=[(0, 'Baja'), (1, 'Mediana'), (2, 'Alta')], default=0, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_responses', to='accounts.support')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
