# Generated by Django 5.1 on 2024-08-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_title_profile_created_at_profile_updated_at_and_more'),
        ('company', '0004_alter_address_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.organization'),
        ),
    ]
