# Generated by Django 5.1 on 2024-08-24 01:22

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('slogan', models.CharField(blank=True, max_length=128, null=True)),
                ('rfc', models.CharField(blank=True, max_length=16, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.address')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('currency', models.CharField(choices=[('MXN', 'MXN - Peso mexicano'), ('USD', 'USD - Dólar estadounidense')], default='MXN', max_length=3)),
                ('vat', models.CharField(choices=[(8, 'Eight Percent'), (16, 'Sixteen Percent')], default=8, max_length=4)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='company.organization')),
            ],
        ),
    ]
