# Generated by Django 5.1 on 2024-08-26 00:46

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id',
            field=models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('folio', models.CharField(blank=True, max_length=16, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='quotation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='company.quotation'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='company.method')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='company.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('overridden_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_services', to='company.quotation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_services', to='company.service')),
            ],
        ),
    ]
