# Generated by Django 5.1 on 2024-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_method_workorder_created_at_workorder_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='currency',
            field=models.CharField(choices=[('MXN', 'MXN - Peso mexicano'), ('USD', 'USD - Dólar estadounidense')], default='MXN', max_length=4),
        ),
    ]
