# Generated by Django 5.0.6 on 2024-06-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=4)),
                ('notas', models.TextField(blank=True, null=True)),
                ('correoss_adicionales', models.TextField(blank=True, help_text='Lista de correos adicionales separados por comas', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_personalizado', models.CharField(max_length=20, unique=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.prospecto')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.concepto')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cotizacion')),
            ],
        ),
    ]
