# Generated by Django 5.0.6 on 2024-06-27 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina_web', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id_personalizado',
            field=models.CharField(default='0001', max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formato', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='accounts.organizacion')),
            ],
        ),
    ]
