# Generated by Django 5.0.6 on 2024-06-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
    ]
