# Generated by Django 5.1 on 2024-08-15 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_predeterminada', models.CharField(choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], default='MXN', max_length=10, verbose_name='Moneda Predeterminada')),
                ('tasa_iva_default', models.DecimalField(decimal_places=2, default=Decimal('0.16'), max_digits=4, verbose_name='Tasa de IVA Predeterminada')),
                ('formato_numero_cotizacion', models.CharField(default='COT-{year}-{seq}', max_length=50, verbose_name='Formato de Número de Cotización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
