# Generated by Django 5.0.6 on 2024-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo',
            name='leyenda',
            field=models.TextField(default='Leyenda predeterminada'),
        ),
    ]
