# Generated by Django 5.1 on 2024-09-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='total',
        ),
    ]
