# Generated by Django 5.0.6 on 2024-06-27 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizacion_alter_cotizacion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
