# Generated by Django 5.0.7 on 2024-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_servicio_nombre_servicio_notificacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=225)),
                ("archivo", models.FileField(upload_to="documentos/pdf/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cotizacion_pdf_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="ordenTrabajo_pdf_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
