# Generated by Django 5.1 on 2024-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_servicio_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='orden_pedido_pdf',
            new_name='orden_cmpra_pdf',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
