# Generated by Django 5.1 on 2024-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cotizacion_tasa_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tasa_iva_default',
            field=models.CharField(choices=[('0.08', '8%'), ('0.16', '16%')], default='0.08', max_length=4, verbose_name='Tasa de IVA Predeterminada'),
        ),
    ]
