# Generated by Django 5.0.7 on 2024-07-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_documento_cotizacion_cotizacion_pdf_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Documento",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="cotizacion_pdf_id",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="ordenTrabajo_pdf_id",
        ),
    ]
