# Generated by Django 5.0.7 on 2024-07-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_concepto_estado_ordentrabajo_concepto_delete_formato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concepto",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="ordentrabajo",
            name="concepto",
        ),
    ]
