# Generated by Django 5.0.6 on 2024-06-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cotizacion_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
    ]
