# Generated by Django 5.0.7 on 2024-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_empresa_rfc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informacioncontacto",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="informacioncontacto",
            name="fax",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
