# Generated by Django 5.0.6 on 2024-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cotizacion_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='id_personalizado',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
