# Generated by Django 5.0.7 on 2024-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_delete_documento_remove_cotizacion_cotizacion_pdf_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cotizacion_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="cotizaciones_pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="direccion",
            field=models.CharField(
                default="Calle Puebla, No. 4990, col. Guillen, Tijuana BC, México, C.P. 22106",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="nombre",
            field=models.CharField(
                default="Ingenieria y Administración Estratégica, S.A. de C.V.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="telefono",
            field=models.CharField(default="(664) 104 51 44", max_length=20),
        ),
    ]
