# Generated by Django 5.1 on 2024-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_configuracionsistema_tasa_iva_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='formato_numero_cotizacion',
            field=models.CharField(choices=[('COT-{year}-{seq}', 'COT-{year}-{seq}'), ('{year}-COT-{seq}', '{year}-COT-{seq}'), ('COT-{seq}', 'COT-{seq}'), ('{seq}', '{seq}')], default='{seq}', max_length=50, verbose_name='Formato de Número de Cotización'),
        ),
    ]
