# Generated by Django 5.0.7 on 2024-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_concepto_estado_remove_ordentrabajo_concepto"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordentrabajo",
            name="conceptos",
            field=models.ManyToManyField(
                related_name="ordenes_trabajo", to="accounts.concepto"
            ),
        ),
    ]
