# Generated by Django 5.1 on 2024-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_configuracionsistema_formato_numero_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
