# Generated by Django 5.0.7 on 2024-07-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ordentrabajo_conceptos"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenTrabajoConcepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otra_descripción", models.TextField()),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.concepto",
                    ),
                ),
                (
                    "orden_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.ordentrabajo",
                    ),
                ),
            ],
            options={
                "unique_together": {("orden_trabajo", "concepto")},
            },
        ),
    ]
