# Generated by Django 5.0.6 on 2024-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_prospecto_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
