# Generated by Django 5.0.7 on 2024-07-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_cotizacion_orden_perdon_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotizacion",
            old_name="orden_perdon_pdf",
            new_name="orden_pedido_pdf",
        ),
    ]
