# Generated by Django 5.0.7 on 2024-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_informacioncontacto_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordentrabajoconcepto",
            name="descripcion_personalizada",
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tasa_iva",
            field=models.DecimalField(decimal_places=2, default=0.08, max_digits=4),
        ),
    ]
