# Generated by Django 5.0.7 on 2024-07-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_ordentrabajoconcepto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordentrabajoconcepto",
            name="cantidad",
        ),
    ]
