# Generated by Django 5.0.6 on 2024-06-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cotizacion_id_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='id_personalizado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
