# Generated by Django 5.0.6 on 2024-07-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_persona_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
