# Generated by Django 5.1 on 2024-09-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cotizacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
