# Generated by Django 5.0.7 on 2024-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_formatocotizacion_imagen_marca_agua_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queja",
            name="archivo_adjunto",
            field=models.FileField(
                blank=True, null=True, upload_to="soporte_adjuntos/"
            ),
        ),
        migrations.AddField(
            model_name="queja",
            name="prioridad",
            field=models.CharField(
                choices=[("Baja", "Baja"), ("Media", "Media"), ("Alta", "Alta")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
