# Generated by Django 5.0.7 on 2024-08-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_remove_ordentrabajoconcepto_descripcion_personalizada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="concepto",
            name="subcontrato",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
