# Generated by Django 5.0.7 on 2024-07-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_ordentrabajoconcepto_cantidad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordentrabajoconcepto",
            old_name="otra_descripción",
            new_name="otra_descripcion",
        ),
    ]
