# Generated by Django 5.1 on 2024-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_concepto_subcontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='subcontrato',
        ),
        migrations.AddField(
            model_name='servicio',
            name='acreditado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='subcontrato',
            field=models.BooleanField(default=False),
        ),
    ]
