# Generated by Django 5.0.7 on 2024-08-15 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_concepto_subcontrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concepto",
            name="subcontrato",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_caducidad",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_solicitud",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
