# Generated by Django 5.0.7 on 2024-07-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_rename_otra_descripción_ordentrabajoconcepto_otra_descripcion",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordentrabajoconcepto",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ordentrabajoconcepto",
            name="orden_trabajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conceptos_orden",
                to="accounts.ordentrabajo",
            ),
        ),
        migrations.AlterField(
            model_name="ordentrabajoconcepto",
            name="otra_descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
