# Generated by Django 5.1 on 2024-09-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizacion_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='regimen_fiscal',
            field=models.CharField(choices=[('612', 'Régimen de Incorporación Fiscal'), ('601', 'Régimen General de Ley Personas Morales'), ('603', 'Régimen de Sueldos y Salarios'), ('605', 'Régimen de Arrendamiento'), ('606', 'Régimen de Actividades Empresariales y Profesionales'), ('607', 'Régimen de Enajenación de Bienes'), ('610', 'Régimen de Personas Morales con Fines no Lucrativos'), ('611', 'Régimen de Consolidación Fiscal')], default='612', max_length=5),
        ),
    ]
