# Generated by Django 5.0.7 on 2024-07-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_ordentrabajoconcepto_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordentrabajo",
            name="conceptos",
        ),
        migrations.DeleteModel(
            name="OrdenTrabajoConcepto",
        ),
    ]
