# Generated by Django 5.1 on 2024-09-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organizacion_regimen_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='rfc',
        ),
    ]
