# Generated by Django 5.0.7 on 2024-07-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_ordentrabajo_conceptos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenTrabajoConcepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_personalizada", models.TextField(blank=True, null=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.concepto",
                    ),
                ),
                (
                    "orden_de_trabajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="accounts.ordentrabajo",
                    ),
                ),
            ],
        ),
    ]
