# Generated by Django 5.1 on 2024-09-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_organizacion_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.organizacion'),
        ),
    ]
