# Generated by Django 5.1 on 2024-09-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Organizacion',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.organizacion'),
            preserve_default=False,
        ),
    ]
