# Generated by Django 5.1 on 2024-09-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_customuser_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_org', to='accounts.direccion'),
        ),
    ]
