# Generated by Django 5.1 on 2024-09-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_organizacion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='first_configuration',
            field=models.BooleanField(default=False),
        ),
    ]
