# Generated by Django 5.1 on 2024-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_empresa_first_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
