# Generated by Django 5.1 on 2024-09-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_organizacion_pagina_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.organizacion'),
        ),
    ]
