# Generated by Django 5.1 on 2024-09-20 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_sucursal_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.organizacion'),
            preserve_default=False,
        ),
    ]
