# Generated by Django 5.1 on 2024-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='regimen_fiscal',
            field=models.CharField(choices=[('612', '612 - Régimen de Incorporación Fiscal'), ('601', '601 - Régimen General de Ley Personas Morales'), ('603', '603 - Régimen de Sueldos y Salarios'), ('605', '605 - Régimen de Arrendamiento'), ('606', '606 - Régimen de Actividades Empresariales y Profesionales'), ('607', '607 - Régimen de Enajenación de Bienes'), ('610', '610 - Régimen de Personas Morales con Fines no Lucrativos'), ('611', '611 - Régimen de Consolidación Fiscal')], default='612', max_length=5),
        ),
    ]
