# Generated by Django 5.1 on 2024-10-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_organizacion_regimen_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='enlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='accounts.cotizacion'),
        ),
    ]
