# Generated by Django 5.1 on 2024-10-15 21:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_organizacion_configuracion_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tipo_de_cambio',
            field=models.DecimalField(default=Decimal('18.00'), decimal_places=2, max_digits=5),
        ),
    ]
