# Generated by Django 5.1 on 2024-10-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_configuracionsistema_tipo_de_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='tipo_de_cambio',
        ),
    ]
