# Generated by Django 5.1 on 2024-10-15 21:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_configuracionsistema_tipo_de_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tipo_de_cambio_dolar',
            field=models.DecimalField(decimal_places=4, default=Decimal('18.0'), max_digits=10),
        ),
    ]
