# Generated by Django 5.1 on 2024-10-15 21:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_configuracionsistema_tipo_de_cambio_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tipo_de_cambio_dolar',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.0'), max_digits=10),
        ),
    ]
