# Generated by Django 5.1 on 2024-10-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_cotizacion_t_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='t_cambio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
