# Generated by Django 5.1 on 2024-10-17 14:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_cotizacion_t_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='t_cambio',
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='tipo_de_cambio_dolar',
            field=models.DecimalField(decimal_places=4, default=Decimal('18.0'), max_digits=10),
        ),
    ]
