# Generated by Django 5.1 on 2024-08-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('cer_file', models.FileField(upload_to='csds/cer/')),
                ('key_file', models.FileField(upload_to='csds/key/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=255)),
                ('uso_cfdi', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sello_cfd', models.TextField()),
                ('sello_sat', models.TextField()),
                ('no_certificado_cfd', models.CharField(max_length=20)),
                ('no_certificado_sat', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='cfdis/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cfdis/pdf/')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.emisor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor')),
            ],
        ),
    ]
