# Generated by Django 5.1 on 2024-09-04 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('cer_file', models.FileField(upload_to='csds/cer/')),
                ('key_file', models.FileField(upload_to='csds/key/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('regimen_fiscal', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=255)),
                ('uso_cfdi', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('xml_timbrado', models.FileField(blank=True, null=True, upload_to='facturas_xmls/')),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='facturas_pdfs/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(choices=[('01', 'Efectivo'), ('03', 'Transferencia electrónica de fondos')], default='03', max_length=5)),
                ('forma_pago', models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], default='PUE', max_length=5)),
                ('uso_cfdi', models.CharField(choices=[('G01', 'Adquisición de mercancias'), ('G03', 'Gastos en general')], default='G03', max_length=5)),
                ('rfc_receptor', models.CharField(max_length=13)),
                ('regimen_fiscal_receptor', models.CharField(max_length=3)),
                ('orden_compra', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_moneda', models.CharField(choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], max_length=100)),
                ('tasa_iva', models.CharField(choices=[('0.08', '8%'), ('0.16', '16%')], max_length=4)),
                ('correos', models.CharField(blank=True, max_length=255, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.almacen')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.cotizacion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sello_cfd', models.TextField()),
                ('sello_sat', models.TextField()),
                ('no_certificado_cfd', models.CharField(max_length=20)),
                ('no_certificado_sat', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='cfdis/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cfdis/pdf/')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.emisor')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.receptor')),
            ],
        ),
    ]
