# Generated by Django 5.1 on 2024-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('01', 'Efectivo'), ('03', 'Transferencia electrónica de fondos'), ('99', 'Por definir')], default='99', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], default='PUE', max_length=5),
        ),
    ]
