# Generated by Django 5.1 on 2024-08-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_servicio_unidad'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('xml_timbrado', models.FileField(blank=True, null=True, upload_to='facturas_xmls/')),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='facturas_pdfs/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.cotizacion')),
            ],
        ),
    ]
