# Generated by Django 5.1 on 2024-09-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_conceptofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csd',
            name='rfc',
        ),
    ]
