# Generated by Django 5.1 on 2024-09-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_forma_pago_alter_factura_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='sucursal',
        ),
    ]
