# Generated by Django 5.1 on 2024-09-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizacion_rfc'),
        ('facturacion', '0003_remove_csd_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='organizacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.organizacion'),
            preserve_default=False,
        ),
    ]
