# Generated by Django 5.1 on 2024-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_delete_cfdi_remove_factura_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='ExchangeRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='ExpeditionPlace',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cfdi_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
