# Generated by Django 5.1 on 2024-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_discount_factura_exchangerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='CfdiSign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='OriginalString',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='SatSign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
