# Generated by Django 5.1 on 2024-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_moneda',
            field=models.CharField(max_length=100),
        ),
    ]
