# Generated by Django 5.1 on 2024-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_factura_tipo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_moneda',
            field=models.CharField(choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], max_length=100),
        ),
    ]
