# Generated by Django 5.1 on 2024-09-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_factura_tipo_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='orden_compra',
        ),
    ]
