# Generated by Django 5.1 on 2024-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_remove_factura_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(choices=[('01', 'Efectivo'), ('02', 'Cheque nominativo'), ('03', 'Transferencia electrónica de fondos'), ('04', 'Tarjeta de crédito'), ('05', 'Monedero electrónico'), ('06', 'Dinero electrónico'), ('08', 'Vales de despensa'), ('12', 'Dación en pago'), ('13', 'Pago por subrogación'), ('14', 'Pago por consignación'), ('15', 'Condonación'), ('17', 'Compensación'), ('23', 'Novación'), ('24', 'Confusión'), ('25', 'Remisión de deuda'), ('26', 'Prescripción o caducidad'), ('27', 'A satisfacción del acreedor'), ('28', 'Tarjeta de débito'), ('29', 'Tarjeta de servicios'), ('30', 'Aplicación de anticipos'), ('31', 'Intermediarios'), ('99', 'Por definir')], default='99', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('PPD', 'Pago en parcialidades ó diferido'), ('PUE', 'Pago en una sola exhibición')], default='PUE', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(choices=[('CN01', 'Nómina'), ('CP01', 'Pagos'), ('D01', 'Honorarios médicos, dentales y gastos hospitalarios.'), ('D02', 'Gastos médicos por incapacidad o discapacidad'), ('D03', 'Gastos funerales.'), ('D04', 'Donativos.'), ('D05', 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).'), ('D06', 'Aportaciones voluntarias al SAR.'), ('D07', 'Primas por seguros de gastos médicos.'), ('D08', 'Gastos de transportación escolar obligatoria.'), ('D09', 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.'), ('D10', 'Pagos por servicios educativos (colegiaturas)'), ('G01', 'Adquisición de mercancias'), ('G02', 'Devoluciones, descuentos o bonificaciones'), ('G03', 'Gastos en general'), ('I01', 'Construcciones'), ('I02', 'Mobilario y equipo de oficina por inversiones'), ('I03', 'Equipo de transporte'), ('I04', 'Equipo de computo y accesorios'), ('I05', 'Dados, troqueles, moldes, matrices y herramental'), ('I06', 'Comunicaciones telefónicas'), ('I07', 'Comunicaciones satelitales'), ('I08', 'Otra maquinaria y equipo'), ('P01', 'Por Definir'), ('S01', 'Sin efectos fiscales')], default='G03', max_length=5),
        ),
    ]
