# Generated by Django 5.1 on 2024-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_factura_forma_pago_alter_factura_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
