# Generated by Django 5.1 on 2024-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_factura_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
