# Generated by Django 5.1 on 2024-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_alter_factura_forma_pago_alter_factura_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.CharField(blank=True, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
