# Generated by Django 5.1 on 2024-10-07 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='ref_cfdi',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='metodo_pago',
            field=models.CharField(choices=[('01', 'Efectivo'), ('03', 'Transferencia electrónica de fondos'), ('99', 'Por definir')], default='99', max_length=5),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
