# Generated by Django 5.1 on 2024-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_remove_comprobante_ref_cfdi_comprobante_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='cfdi_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
