# Generated by Django 5.1 on 2024-10-22 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_configuracionsistema_moneda_predeterminada_and_more'),
        ('facturacion', '0020_comprobante_pdf_file_comprobante_xml_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csd',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csd', to='accounts.organizacion'),
        ),
    ]
