export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAIL = "REFRESH_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS";
export const ACTIVATE_ACCOUNT_FAIL = "ACTIVATE_ACCOUNT_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_FAIL";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_FAIL = "SET_FAIL";
export const LOGOUT = "LOGOUT";
export const GUEST_VIEW = "GUEST_VIEW";

export type AuthActionTypes =
  | typeof LOGIN_SUCCESS
  | typeof LOGIN_FAIL
  | typeof GOOGLE_AUTH_SUCCESS
  | typeof GOOGLE_AUTH_FAIL
  | typeof AUTHENTICATED_SUCCESS
  | typeof AUTHENTICATED_FAIL
  | typeof USER_LOADED_SUCCESS
  | typeof USER_LOADED_FAIL
  | typeof REFRESH_SUCCESS
  | typeof REFRESH_FAIL
  | typeof CHANGE_PASSWORD_SUCCESS
  | typeof CHANGE_PASSWORD_FAIL
  | typeof SIGNUP_SUCCESS
  | typeof SIGNUP_FAIL
  | typeof ACTIVATE_ACCOUNT_SUCCESS
  | typeof ACTIVATE_ACCOUNT_FAIL
  | typeof PASSWORD_RESET_SUCCESS
  | typeof PASSWORD_RESET_FAIL
  | typeof PASSWORD_RESET_CONFIRM_SUCCESS
  | typeof PASSWORD_RESET_CONFIRM_FAIL
  | typeof SET_SUCCESS
  | typeof SET_FAIL
  | typeof LOGOUT
  | typeof GUEST_VIEW;
