# Generated by Django 5.1 on 2024-08-24 01:22

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterMethod',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalCustody',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('priority', models.CharField(choices=[('15 business days', 'A'), ('8 to 10 business days', 'B'), ('3 to 5 business days', 'C')], default='15 business days', max_length=25)),
                ('sample_type', models.CharField(choices=[('Composition', 'Composition'), ('Spot', 'Spot')], default='Composition', max_length=15)),
                ('final_disposition', models.CharField(choices=[('Return to client', 'Return To Client'), ('Total destruction', 'Total Destruction'), ('Waste disposal', 'Waste Disposal'), ('Sewer disposal', 'Sewer Disposal')], default='Return to client', max_length=20)),
                ('observations', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_custody', to='company.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='company.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='lab.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('sampling_datetime', models.DateTimeField(blank=True, null=True)),
                ('state_of_matter', models.CharField(choices=[('Liquid', 'Liquid'), ('Solid', 'Solid'), ('Gas', 'Gas'), ('Other', 'Other')], default='Solid', max_length=7)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=4)),
                ('num_containers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filter_method', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='lab.filtermethod')),
                ('internal_custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lab.internalcustody')),
            ],
        ),
        migrations.CreateModel(
            name='SubEquipment',
            fields=[
                ('id', models.CharField(default=core.utils.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_equipments', to='lab.equipment')),
            ],
        ),
    ]
