# Generated by Django 5.1 on 2024-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='filtermethod',
            options={'ordering': ['-created_at'], 'verbose_name': 'FilterMethod', 'verbose_name_plural': 'FilterMethods'},
        ),
        migrations.AlterModelOptions(
            name='internalcustody',
            options={'ordering': ['-created_at'], 'verbose_name': 'InternalCustody', 'verbose_name_plural': 'InternalCustodies'},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Laboratory', 'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterModelOptions(
            name='subequipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'SubEquipment', 'verbose_name_plural': 'SubEquipments'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filtermethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtermethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internalcustody',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internalcustody',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subequipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
